variables:
  - name: WINDOWS_BASEKIT_URL
    value: https://registrationcenter-download.intel.com/akdlm/irc_nas/17453/w_BaseKit_p_2021.1.0.2664_offline.exe
  - name: WINDOWS_DPCPP_COMPONENTS
    value: intel.oneapi.win.dpcpp-compiler
  - name: python.version
    value: '3.9'
  - name: PKG_VERSION
    value: '2021.2.0'


jobs:
- job: Linux_DPCPP
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
      sudo add-apt-repository -y "deb https://apt.repos.intel.com/oneapi all main"
      sudo apt-get update
      sudo apt-get install                  \
          intel-oneapi-common-vars          \
          intel-oneapi-common-licensing     \
          intel-oneapi-dpcpp-cpp-compiler   \
          intel-oneapi-dev-utilities        \
          intel-oneapi-libdpstd-devel
      sudo bash -c 'echo libintelocl.so > /etc/OpenCL/vendors/intel-cpu.icd'
      sudo mv -f /opt/intel/oneapi/compiler/latest/linux/lib/oclfpga /opt/intel/oneapi/compiler/latest/linux/lib/oclfpga_
    displayName: 'apt-get'
  - script: |
      export DPCPPROOT=/opt/intel/oneapi/compiler/latest
      export PKG_VERSION='$(PKG_VERSION)
      export NO_DIST=1
      export ARGS=1
      pip install -r requirements-dev.txt
      ./conda-recipe/build.sh
    displayName: daal4py build
  - script: |
      pip install -r requirements-test.txt
      ./conda-recipe/run_test.sh
    displayName: daal4py testing

- job: MacOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      export PKG_VERSION=$(PKG_VERSION)
      export NO_DIST=1
      export ARGS=1
      pip install -r requirements-dev.txt
      ./conda-recipe/build.sh
    displayName: daal4py build
  - script: |
      pip install -r requirements-test.txt
      ./conda-recipe/run_test.sh
    displayName: daal4py testing

- job: Windows_DPCPP
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: .ci/scripts/install_windows.bat $(WINDOWS_BASEKIT_URL) $(WINDOWS_DPCPP_COMPONENTS)
    timeoutInMinutes: 15
    displayName: oneAPI environment
  - script: |
      set "DPCPPROOT=C:\Program Files (x86)\Intel\oneAPI\compiler\latest"
      set PKG_VERSION=$(PKG_VERSION)
      set NO_DIST=1
      pip install -r requirements-dev.txt
      call conda-recipe\bld.bat
    displayName: daal4py build
  - script: |
      pip install -r requirements-test.txt
      call conda-recipe\run_test.bat
    displayName: daal4py testing
